env = Environment(CCFLAGS='-g')
env.ParseConfig('pkg-config --cflags --libs libpulse')

env.Program('pulsedevicelist.c')

env.Program('pulseevent.c')

env.Program('pulsecard.c')

env.Program('pulsevolume.c')

env.Program('pulseserverinfo.c')
