env = Environment(CCFLAGS='-g')
env.ParseConfig('pkg-config --cflags --libs gtk+-2.0 libpulse')

env.Program('cgtk.c')

env.Program('pulsedevicelist.c')

env.Program('pulseevent.c')

env.Program('pulsecard.c')

env.Program('pulsevolume.c')

env.Program('pulseserverinfo.c')

env.Program('pulsestream_record.c')
